#ifndef _GLOBAL_VALUES_H_
#define _GLOBAL_VALUES_H_
extern float u1[512];
extern float u2[512];
extern float u3[512];
extern float i1[512];
extern float i2[512];
extern float i3[512];
extern float u1_rms_2s;
extern float u2_rms_2s;
extern float u3_rms_2s;
extern float i1_rms_2s;
extern float i2_rms_2s;
extern float i3_rms_2s;
extern float voltage_A_harmonic_2s;
extern float current_A_harmonic_2s;
extern float voltage_B_harmonic_2s;
extern float current_B_harmonic_2s;
extern float voltage_C_harmonic_2s;
extern float current_C_harmonic_2s;
extern float active_power_2s;
extern float reactive_power_2s;
extern float apparent_power_2s;
extern float power_factor_2s;
extern float frequency_10s;
extern float voltage_overdeviation_10s;
extern float voltage_underdeviation_10s;
extern float voltage_unblance_10s;
extern float current_unblance_10s;
extern float voltage_A_fft_2s[10];
extern float current_A_fft_2s[10];
extern float voltage_B_fft_2s[10];
extern float current_B_fft_2s[10];
extern float voltage_C_fft_2s[10];
extern float current_C_fft_2s[10];
//extern float u1_filter[512];//
//extern float u2_filter[512];//
//extern float u3_filter[512];//
//extern float i1_filter[512];//
//extern float i2_filter[512];//
//extern float i3_filter[512];//
//extern float u1_rms[50];
//extern float u1_rms_temp[10];
//extern float u2_rms_temp[10];
//extern float u3_rms_temp[10];
//extern float i1_rms_temp[10];
//extern float i2_rms_temp[10];
//extern float i3_rms_temp[10];
//extern float voltage_A_fft_temp[2][10];
//extern float voltage_B_fft_temp[2][10];
//extern float voltage_C_fft_temp[2][10];
//extern float current_A_fft_temp[2][10];
//extern float current_B_fft_temp[2][10];
//extern float current_C_fft_temp[2][10];
//extern float voltage_unblance_temp[10];
//extern float current_unblance_temp[10];
//extern float active_power_temp[10];
//extern float reactive_power_temp[10];
//extern float apparent_power_temp[10];
# endif
